name: ci/cd
on:
  push:
    branches: [main]

jobs:
  read_version_from_node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read version
        id: read_version
        uses: devecorsoft/read-version@main
        with:
          destination: "node"

      - name: Echo version
        run: |
          echo ${{ steps.read_version.outputs.version }}

  read_version_from_gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read version
        id: read_version
        uses: devecorsoft/read-version@main
        with:
          destination: "gradle"

      - name: Echo version
        run: |
          echo ${{ steps.read_version.outputs.version }}

  read_version_from_pip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read version
        id: read_version
        uses: devecorsoft/read-version@main
        with:
          destination: "pip"

      - name: Echo version
        run: |
          echo ${{ steps.read_version.outputs.version }}

  read_version_from_git_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read version
        id: read_version
        uses: devecorsoft/read-version@main
        with:
          destination: "git-tag"

      - name: Echo version
        run: |
          echo ${{ steps.read_version.outputs.version }}
